### ISSUE TITLE
[feature request] is it possible to add an arrow for suggested moves

### ISSUE THREAD

**Issue by ioweb-gr** [billforsternz/tarrasch-chess-gui#18]
Is it possible when the engine is kibitzing to show an arrow for the suggested next move on the playing side? 

For example if it suggests for White to open up with King's pawn at E4, before the white move is made, it will show a green arrow pointing from the pawn in E2 towards E4. 

It would make it much more user friendly when training if it's not really hard to implement.

**Comment by billforsternz** [comment]
Hmmm, a bit like the Lichess analysis board right? I am not convinced this is a really important feature. Implementing arrows involves tricky graphics programming (not my strength at all) which is why currently you never see an arrow in Tarrasch. Hopefully one day I'll implement arrows, but when I do the priorities will be optionally highlighting the last move, and allowing arrow annotations (i.e. the user can freely add arrows as highlights for whatever reason). I think your own example shows why I think the "top computer move" arrow is not compelling. In most positions, definitely including the starting position, there's more than one contender to be the "best move". I'd only want the engine throwing up an arrow if there's one and only one obviously best move in the position. Even determining that condition is not trivial. For example one side is winning easily and the top move is a complicated forcing move that's +18 (say) and the second move starts a mass exchange leading to a trivial win but is +10 (say). To my mind the second move is a much better *human* move, even though the computer thinks it's 800 centipawns worse!

**Comment by ioweb-gr** [comment]
I see. I was more thinking of how droidfish shows the arrows on both sides. It has many arrows to help out that you can turn on and off. For example 

- it will suggest the best move and the second move after that while showing the estimated responses from the opponent from what I can see. 
- it will mark piece exchanges with different color 
- it will show when a piece is attacked 

It's very user friendly because you can play as you like against stockfish and do your own choices but still have the option to explore what it suggest in an easy manner and then decide if it's better than your move for your playing style or get you out of a pinch :)

But I see what you mean and I hoped it wouldn't be too hard to implement.  Highlighting the last move is also very important though, I agree.

**Comment by friscodelrosario** [comment]
Long ago, when ICC was the only server in town, I learned to use its command-line arrow and circle features for real-time analysis with students on the other end. These days the clients make that easier, I see, which makes sense because thousands of people watch chess games now instead of two.

The OP's request puzzled me at first because Tarrasch GUI isn't designed for that. But now I see the highlights are suggestions during analysis and play with an engine. and that sorta floored me because I didn't think people actually played chess against their computers anymore. I can see how a player would benefit from such highlights, but I think it's outside the scope of the Tarrasch project. And Bill is right about top computer moves sometimes (or often) making no sense to humans, though a move .0000002 worse would fit with general principles.

**Comment by ioweb-gr** [comment]
I mostly play for fun while waiting in queues or before going to bed so I'm not that advanced in chess. However as I play, I really like how droidfish shows me moves when I'm puzzled and I can also undo to see why it's path was better than mine. I can honestly say that by replaying the paths stockfish suggested, it has made me better assess the situations. So yeah I'm probably a small use case but still I thought I'd throw in the idea :)
