### ISSUE TITLE
Docs could use something about Log feature

### ISSUE THREAD

**Issue by friscodelrosario** [billforsternz/tarrasch-chess-gui#25]
I don't know what log.pgn is logging. Nothing in webpage Features section about it.

Then multiple log files are in home folder, but a Logs folder would be tidy.

**Comment by billforsternz** [comment]
I quite like having undocumented pleasant surprises for the user. The log file is a configurable option. It's right there in the Options menu, not a secret. The help button for that options panel explains it, and you can turn it off if you really want to for some reason (on any PC made since 1990 or so there's more than enough storage to mean turning it off has no practical benefit). It's nice that you don't have to ask for it to happen, it happens by default. And it means sometimes you can go back and find things that you might otherwise have lost. Basically I save any game that you've had open (and maybe edited/worked on? - I can't quite remember myself). Basically I am very happy with the existing behaviour, except;

1) I'd love to present the log file games in reverse order.
2) I'd like to refine slightly how things work when you have the log file open. For example no need to prompt the user to save unused work in the log file (as there it will be saved regardless).
