### ISSUE TITLE
The Initial setup step dialogues are unresponsive

### ISSUE THREAD

**Issue by Ivoz** [billforsternz/tarrasch-chess-gui#3]
It's almost impossible to move the dialogue around, interact with it, click on close or cancel etc, ALT+TAB back and forth between it and other windows, while it is working.

Maybe it is a situation where the work could be done on a separate thread, so the GUI dialogue itself remains responsive? (I am guessing at a solution)

For now it's sort of off-putting for a new user, when they first start the program up, and this dialogue is there but seems to be non-interactable.

You may also want to have a Wizard-style "first run" dialogue, or just something to say "Tarrasch is now going to generate a whole lot of stuff on its first run, please be patient" to inform the user why this big load is going to happen / happening.

**Comment by billforsternz** [comment]
I agree that my current approach is absolutely horrible and not suitable for anything beyond alpha/demo. Basically this was a dead rat that had to be swallowed if I was going to deliver something people could actually play with before the end of 2015.

**Comment by billforsternz** [comment]
Fixed with Tarrasch V3 Alpha 2016-03-12.a. Basically this required reworking the whole database subsystem but it was totally worth it. Instead of ridiculously large database files with every position in every game indexed - I now prefer to search all games in the database on the fly - in other words I play through all the games looking for the searched for position. This means the database files are smaller than the input .pgn files, as they should be. This in turn means I prefer to ship the demonstration database binary instead of the equivalent .pgn file, completely avoiding the initial conversion stage. Other benefits of this are that the demo ships with a genuinely useful demo database instead of a puny one not fit for purpose. And when you do need to generate databases, it's much faster.
