### ISSUE TITLE
Make Kibitzer have an easy to see & use / prominent, on /off state

### ISSUE THREAD

**Issue by Ivoz** [billforsternz/tarrasch-chess-gui#4]
My main use for a chess GUI is casually analysing games and moves to find out reasoning behind moves or moves-that-weren't-made. Or even run an engine on a current position in a live classic-time game that's happening between top players, for example.

For this, starting and stopping a kibitzer on a position is one of my biggest use cases.

Suggestions:

A) In general, maybe the GUI buttons could be larger. An option for their size would be even better. People with different DPI monitors might want larger or smaller buttons purely for readability / clickability as well

B) Have the kibitzer button have a visible [activated / deactivated] state, i.e pressed or not pressed, etc. To show when the engine is running or not.

C) Perhaps have a button to "Start kibitzer" in the Start area (next to "Setup Position" "Play White", "Play Black", etc)

Lastly, I know many people not familiar with computer chess can tend to have no idea what the term "kibitzer" means, it can be confusing to them. It maybe be more recognisable to replace it with "Engine" or even the name of the engine that will run.

E.g, "Run Stockfish", "Stop Stockfish", etc.

**Comment by billforsternz** [comment]
Good suggestions all. For a while i've been contemplating a refresh that would see bigger buttons and elimination of the three clunky text buttons below the board - they don't quite deserve their outsize presence and if I had better/bigger buttons up top they could be shifted there. I like the idea of the kibitzer button having state (for what it's worth I explain the kibitzer terminology on my website - I know it's not worth much). Incidentally I really wanted to have start/stop kibitzer as a fourth text button and finally rejected the idea only because the other three big buttons are key features when you first start the program. I hated the idea of a new user trying the fourth button in the opening position as well (and seeing dreary computer analysis of said position).

**Comment by billforsternz** [comment]
The Engine Analysis tab eliminates this problem.
