### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Ivoz** [billforsternz/tarrasch-chess-gui#5]
I have a few suggestions for making a nicer UI:

A) Use nicer icons.

There are many many nice icon packs around nowadays, many are SVG so they could be rasterized / rendered to any size. It would be nice to use some nice modern high-res ones. Just googling:

[Ionicons](http://ionicons.com/) - [Flat Icons](http://www.flaticon.com/packs/) - [Font Awesome](https://fortawesome.github.io/Font-Awesome/) - [FontEllo](http://fontello.com/)  - [Icomoon](https://icomoon.io/) (all free for OSS & commercial use, AFAICT)

If you have some custom icons you'd like to use, maybe you could even get them crowd sourced by a generous designer.

B) Allow more font options

Currently there seems to be only "Use larger font in move window". It would be nice to be able to select a font using a font dialogue, and especially a font size. In this image, 

![tarrasch fonts](http://i.imgur.com/dHboj02.png)

You can see the font for "2 book moves" in the green button looks horrible, and I don't think the small bolded font for the moves is _especially_ readable. You could either look to implementing the nicest default fonts for modern OS's (e.g Windows uses Segio UI for most stuff) and/or have a default font, you can get plenty of free/OSS ones from [Google Fonts](https://www.google.com/fonts)

C) Allow the move listing window to list fonts numbered down the page orderly, like
1. e4 e5
2. Nf3 Nc6
3. Bc4 Bc5

etc, with sub-lines coming up in between the main lines, perhaps slightly indented. E.g you can see [BabasChess using this style here](http://screenshots.en.sftcdn.net/en/scrn/299000/299756/babaschess-3.png).

Cheers, happy new year

**Comment by billforsternz** [comment]
A) and B) would definitely be major improvements. Probably medium term rather than short term. Basically wxWidgets constrains me a lot in these areas, although it makes the whole program possible so I can't complain too much. You're absolutely right, the book moves font does look absolutely horrible and this has been bothering me literally for years. I could and should have another go at fixing that one. C) I could countenance as some kind of option but it's definitely not my preference, it is too profligate with space. See the screenshot on triplehappy.com to see how Tarrasch displays dense chess content - I'm very happy with my approach here.

**Comment by Antaniserse** [comment]
If i may chime in, it would be also nice to have a single options dialog... i'm not too familiar with wxWidgets, but i guess something like this, which uses just basic controls, shouldn't be a problem
[Options mockup](http://imgur.com/9VVnQ4i)

Also, how about using the new tabbed approach also in the database window for fast switching between the different workset of games?
[Database mockup](http://imgur.com/UAwL9Hs)

**Comment by billforsternz** [comment]
Nice suggestions Antaniserse. I am not sure of the github etiquette of dealing with issues (this is the first time I've had issues). I'm taking a few weeks off but then maybe I should use github issues to organise the next round of progress, including documenting my own priorities etc. Actually my number one priority is making the whole thing a little more developer friendly so that I can get some help on pushing the thing forward.

**Comment by Antaniserse** [comment]
I'm not sure either if there's an actual etiquette for that... now, those are mainly suggestions more than actual issues with the code, so you might aknowledge these and consider them 'closed' or you can choose to keep them open until your next UI revision, whenever you feel like it.

I agree however on the "developer friendly" priority; now, i can hold my own in .NET but I'm really bad at C++ so i'm  not your best target for that, but I admid i couldn't get the source to work; got wxWidgets, copied the relevant includes, fired up VS 2015 but still got stuck with some '*..\\..\\..\lib\vc120 [or something like that]*' folder reference which i could not figure out for the life of me ;)

**Comment by billforsternz** [comment]
Ouch, frankly I'm not surprised about the visual studio issues. wxWidgets.org now provide precompiled libraries for a few versions of Visual Studio. As part of the "developer friendly" thing I will include these in my repository with appropriately updated solution files etc. Oh, and I'll eliminate lots of warnings and generally tighten things up. The actual program functionality stands up pretty well at the moment I think (I've been dogfooding intensively with good effect), so encouraging some dev help makes a lot of sense I think.

**Comment by billforsternz** [comment]
I am closing this issue as it refers to an outdated form of the program. The UI of Tarrasch has been refreshed since this issue was posted and if interested people wish to make further UI suggestions they are most welcome.
